name: Pacman Contribution

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Pacman animation
        uses: Platane/snk@v3
        with:
          github_user_name: nexordevs
          outputs: |
            dist/pacman.svg?palette=github-dark&color_snake=00F7FF&color_dots=#05080f,#1a1a2e,#16213e,#0f3460,#00F7FF

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
