name: 🐍 Cyberpunk Fade Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ⚡ Generate Fade Snake
        uses: Platane/snk@v3
        with:
          github_user_name: nexordevs
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#00F7FF&color_dots=#2a2f36,#3a3f46,#00F7FF,#7C3AED,#3a3f46

      - name: 🚀 Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
